---
kind: pipeline
type: docker
name: default

workspace:
  base: /go
  path: src/git.joeslife.net/joseph/quicktlsproxy

environment:
  CGO_ENABLED: 0

steps:
- name: dep
  image: golang:latest
  commands:
    - go get -v
    - go test

- name: build
  image: golang:latest
  commands:
    - go build

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key:
      from_secret: gitea_token
    base_url: https://git.joeslife.net
    files: quicktlsproxy
    checksum: sha256
  when:
    event: tag

- name: docker_image
  image: plugins/docker
  settings:
    repo: dsbaha/quicktlsproxy
    auto_tag: true
    username:
      from_secret: dockerhub_user
    password:
      from_secret: dockerhub_password
